name: portal-api

services:
  portal-api:
    container_name: portal-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_URL: http://localhost:8015
    ports:
      - "8015:8000"
    volumes:
      - portal_storage:/var/www/html/storage

volumes:
  portal_storage:
    name: portal-api-storage
